### ISSUE TITLE
paratest reports incorrect coverage data

### ISSUE THREAD

**Issue by justechn** [brianium/paratest#160]
I am having a problem with the code coverage reports that are produced by paratest. When I run my test directly in phpunit i get 100% coverage. When I run the test in paratest I get 82%.

phpunit
![phpunit](https://cloud.githubusercontent.com/assets/1508662/6695351/3f61761c-cca6-11e4-91f2-18c40d2206ee.PNG)

paratest
![paratest](https://cloud.githubusercontent.com/assets/1508662/6695354/413c358a-cca6-11e4-9fdd-af1266d32049.png)

**Comment by aik099** [comment]
This sounds like #89. I have the same problem with latest PHPUnit version. The opening/closing braces of class/method are reported as non-covered by paratest, while PHPUnit own coverage report doesn't mention lines with them at all.

Maybe coverage merger assumes that all lines are not covered from the start, but that's not true. Maybe the xdebug stopped to report braces in it's report and PHPUnit just adapted somehow.

Part from `clover.xml` generated by ParaTest:
```xml
<line num="53" type="stmt" count="0"/>
```

**Comment by ryanmc2033** [comment]
any update on this?

**Comment by julianseeger** [comment]
Nope.
It must be an issue deep in the xdebug code. Looks buggy to me... In the [original report](https://github.com/brianium/paratest/issues/160#issue-62488920), the closing braces my make sense, but line 86 and 93 should be green and aren't. Merging multiple buggy reports to one that is not buggy seems bad.

**Comment by aik099** [comment]
Are we using PHP_CodeCoverage native merger or our own merger?

**Comment by julianseeger** [comment]
The native one.
https://github.com/brianium/paratest/blob/master/src/ParaTest/Coverage/CoverageMerger.php#L34
\ParaTest\Coverage\CoverageMerger is only a wrapper...

**Comment by GuilhermeGuitte** [comment]
any update on this? (2)

**Comment by julianseeger** [comment]
I think this issue has to be tested in isolation on https://github.com/sebastianbergmann/php-code-coverage and if it is really independent of paratest, it has to be reported/fixed upstream in that project.

**Comment by rscafi** [comment]
I can confirm that, at least for my use case (and @GuilhermeGuitte), this is no longer a bug. I guess that php-code-coverage has been fixed and the coverage is now correct.

**Comment by julianseeger** [comment]
@justechn can you confirm that, too?

**Comment by justechn** [comment]
I am no longer working on the project that I reported this from so I cannot confirm. I am ok if you close it.
