### ISSUE TITLE
remove PHP 5.3 from build matrix?

### ISSUE THREAD

**Issue by julianseeger** [brianium/paratest#161]
We still keep up the 5.3 compatibility as it is part of the travis build matrix. Is this still neccessary when php 5.3 is [not officially supported anymore](http://php.net/archive/2014.php#id2014-08-14-1)? 

According to [this blog](http://blog.pascal-martin.fr/post/php-versions-stats-2014-10-en.html) from october 2014, PHP5.3 is still used by about 44% of all (observed) webservers. Would it be
a) positive to no longer support php5.3 at paratest to support upgrades to newer versions?
or
b) negative because so many sites still use it?

It is not that a big deal to use `array()` instead of `[]` etc, but it gets annoying over time and maybe we are sending the wrong signals by still supporting it. Any thoughts?

**Comment by fiddur** [comment]
Normally I would say drop support of too old versions.  We still use it here, but dropped support from external libs would force us to upgrade, and that would be good :)

**Comment by localheinz** [comment]
:+1:

**Comment by julianseeger** [comment]
As soon as the build is back to green, 5.3 will be removed from the build matrix and 5.4 will follow at EOL (15 Sep 2015 http://php.net/supported-versions.php)
