### ISSUE TITLE
Do you plan to add support for newer phpunit version soon?

### ISSUE THREAD

**Issue by jboffel** [brianium/paratest#165]
Latest version stable is 4.7 so 3.7.8 is already quite old...

**Comment by brianium** [comment]
the `>=` constraint just says it supports 3.7.8 and higher. This includes new versions of PHPUnit as well

**Comment by jboffel** [comment]
Good catch, sorry I misread the constraint... I've been surprised when executing it because it behaves differently than simply running phpunit alone in my use case and I thought it was due to some unsupported tag from the phpunit.xml. But it is probably coming from a different reason as paratest is using phpunit 4.7.5 with the last installation.
Thanks for your help!
