### ISSUE TITLE
fix the build

### ISSUE THREAD

**Issue by julianseeger** [brianium/paratest#166]
2 issues:
* hhvm-nightly no longer exists (has to be removed from the travis.yml)
* phpunit has corrected (?) it's output for warnings. They show up in the summary as tests, assertions and failures ... thus, the test https://github.com/brianium/paratest/blob/b107f324f01f1a5557589b946558a2a94e282c00/test/functional/PHPUnitTest.php#L311 has to be adjusted accordingly. (Looks strange that warnings show up as `FFWW`)

**Comment by localheinz** [comment]
@julianseeger 

Here's a PR for removing the `hhvm-nightly` from the build matrix: https://github.com/brianium/paratest/pull/172.

**Comment by julianseeger** [comment]
the issue related to warnings was propably caused by https://github.com/sebastianbergmann/phpunit/commit/821427232dd4028f8a13832219c4d73c73b3d879 which is a fix for https://github.com/sebastianbergmann/phpunit/issues/1317
phpunit 4.7.2 works but 4.7.3 does not

**Comment by julianseeger** [comment]
fixed
