### ISSUE TITLE
PHPStorm setup manual

### ISSUE THREAD

**Issue by theNailz** [brianium/paratest#167]
Has anyone been able to setup PHPStorm with paratest? I haven't found a place to define my alternative phpunit executable.

**Comment by chriscalifornia88** [comment]
Set it up as a PHP Script Run/Debug Configuration.

File: 'vender/bin/paratest'
Arguments: '--processes=6 --configuration=', etc

**Comment by calebfavor** [comment]
Was anyone actually able to get this to work? I've been at it for 2 hours and it seems to be impossible to get paratest to run inside phpstorm using a PHP Script configuration or any other configuration.

**Comment by gabrielpreston** [comment]
It took me about a minute just now to add paratest under Tools->External Tool, not sure if that's ideal for what you are looking to do though.

**Comment by calebfavor** [comment]
@gabrielpreston - Mind sharing the details of how you setup the external tool and run configuration? I can't seem to get it going.

**Comment by gabrielpreston** [comment]
In the application's settings, I went down to the Tools section, and then External Tools. I added a new one and named it `paratest`.

Then, under `Tool settings`:
For `Program`, I browsed to where paratest was installed
For `Parameters', I set mine to `-f -p 5`
For `Working directory`, I set that to the directory I would have been in had I tried to run paratest myself from the command line.

**Comment by calebfavor** [comment]
@gabrielpreston - That work perfectly, thank you!

**Comment by gabrielpreston** [comment]
Great! This is the most simplistic way to get it done. There may be some things you can tweak with it to specify specific groups or test suites you want to run, but I didn't spend the time to look into that.

**Comment by michaelst** [comment]
Is there a way to get this to work with a vagrant setup? I have phpunit setup with the remote interpreter but can't figure out how to do that with these suggested options.

**Comment by Nossnevs** [comment]
![paratest](https://user-images.githubusercontent.com/5055546/33890915-d1d49cc2-df54-11e7-8ffb-9efaf5b87f3b.jpg)

**Comment by meyer59** [comment]
For anyone coming here, as of today, Paratest is supported by phpstorm [https://www.jetbrains.com/phpstorm/whatsnew/2022-3/](https://www.jetbrains.com/phpstorm/whatsnew/2022-3/)
