### ISSUE TITLE
Bug when trying to pass --configuration parameter with a folder including space in the name

### ISSUE THREAD

**Issue by jboffel** [brianium/paratest#168]
I finally got some time to work on the difference of behavior I observed between phpunit and paratest. The reason is below:

I traced the execution of phpunit with strace and when the folder is including space you can see the invocation of phpunit as follow:

```
execve("/bin/phpunit", ["...", "--configuration", "some", "Folder/phpunit.xml", "--bootstrap", "some", "Folder/bootstrap.php", "--log-junit", "/tmp/PT_bgrBRM", "SomeParameter", "SomeTestPath"]
```

instead of:

```
execve("/bin/phpunit", ["...", "--configuration", "some Folder/phpunit.xml", "--bootstrap", "some Folder/bootstrap.php", "--log-junit", "/tmp/PT_bgrBRM", "SomeParameter", "SomeTestPath"]
```

The result is an InvalidArgumentException with the current issue.

**Comment by jboffel** [comment]
Never mind, my version was already old, I tried with the last dev-master and the bug is already fixed.

**Comment by julianseeger** [comment]
anyways, 0.12.3=dev-master so no need to fix on dev-master ;)
