### ISSUE TITLE
paratest ignores the <exclude> tags from the phpunit config.xml

### ISSUE THREAD

**Issue by ThomasDelteil** [brianium/paratest#180]
As per the title, paratest ignores the type of tags in the `<testsuite>` node
- `<exclude>`
- `<file>`
- `<directory>`

They are treated without distinction

**Comment by rscafi** [comment]
:+1:, it was driving me crazy

**Comment by ThomasDelteil** [comment]
I actually have a fix somewhere for that, I will see if I can get it in order and properly tested and issue a PR. As far as I remember I had to refactor a few classes to make it work properly though

**Comment by ThomasDelteil** [comment]
@rscafi I have added tests and opened a PR. That would be helpful if you had time to checkout this branch and test it against your config see if it behaves correctly:
https://github.com/ThomasDelteil/paratest/tree/fix_exclude_folder
