### ISSUE TITLE
XML output cannot be parsed by Jenkins

### ISSUE THREAD

**Issue by SvenRtbg** [brianium/paratest#199]
When running a test suite, the resulting XML is correctly parsed by Jenkins when only using PHPUnit, but fails when using Paratest.

The build is triggered by a Phing build.xml

```
<property name="PARATEST_CALL" value="&quot;${project.basedir}/vendor/bin/paratest&quot;"/>
<property name="PARATEST_OPTIONS" value="-p 8"/>
<property name="PHPUNIT_CALL" value="&quot;${project.basedir}/vendor/bin/phpunit&quot;"/>

<exec command="cd tests/integration; ${PARATEST_CALL} ${PARATEST_OPTIONS} --phpunit ${PHPUNIT_CALL} --log-junit &quot;${BUILD_DIRECTORY}/results-integration.xml&quot;" passthru="true" checkreturn="true"/>
```

This fails.

However, when I fix the output file just a little bit, it works:

```
<exec command="cd tests/integration; ${PARATEST_CALL} ${PARATEST_OPTIONS} --phpunit ${PHPUNIT_CALL} --log-junit &quot;${BUILD_DIRECTORY}/results-integration.xml&quot;; ret=$?; sed -i -e 's/line=&quot;&quot;/line=&quot;0&quot;/' ${BUILD_DIRECTORY}/results-integration.xml; (exit $ret);" passthru="true" checkreturn="true"/>
```

The important part is the SED operation (the surrounding part is just saving the exit code):

sed -i -e 's/line=&quot;&quot;/line=&quot;0&quot;/'

Line numbers always have to be integers, they cannot be empty.

I'm using Paratest 0.13.2 and PHPUnit 4.8.23, but the problem has been bugging me for a long time (read: has been present in older versions of both softwares as well).

**Comment by SvenRtbg** [comment]
The Jenkins xunit plugin has a schema for the result.xml files. See https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/phpunit-2.0.xsd

**Comment by mabu-github** [comment]
Another solution could be not to write out the "line" attribute because it is optional.
`<xs:attribute name="line" type="xs:integer" use="optional"/>`

**Comment by SvenRtbg** [comment]
https://github.com/brianium/paratest/issues/19 looks related to this.

**Comment by michaelbutler** [comment]
I hope that my PR fixes this problem. Please confirm if you can by checking out this branch and using it in jenkins.

**Comment by julianseeger** [comment]
https://scrutinizer-ci.com/g/brianium/paratest/inspections/5d2bda90-85d1-4620-b7ee-a2c90ed6d589
> No notable changes
There were no notable changes in the changeset which was inspected.

so it's either not working anymore or it has nothing to say ;)

**Comment by michaelbutler** [comment]
@julianseeger requesting a close on this issue, as far as we know this specific thing has been resolved.
