### ISSUE TITLE
flock() testing 

### ISSUE THREAD

**Issue by mmamedov** [brianium/paratest#205]
I am testing code that needs to acquire file lock using PHP's flock (LOCK_EX | LOCK_NB), paratest isn't able to catch locks.

When test is run with method output testing using assertEquals true or false, it always returns true - as if locking isn't activated at all.

Interesting thing however:  if I uncomment sleep(1) line inside the code, paratest prints correct output, saying that 1 assert was true(the one that acquired Lock) and 4 others were false. 

This is the only test method in my test class. I have 5 same test classes testing in parallel. 

```php
public function WriteUsingLock() {
$fp = fopen('file.txt', 'c');

if (flock($fp, LOCK_EX | LOCK_NB)) {
 // if sleep is uncommented paratest tests correctly. By correctly I mean test is failing exactly 4 times,
 // because lock wasn't acquired.
 //sleep(1); 

 //write to file and release lock ...
 flock($fp, LOCK_UN);
}
else {
  return false;
}
return true;
}
```

Any ideas?

**Comment by julianseeger** [comment]
Hard to say without knowing your exact test classes but it looks like you assume all tests start at exactly the same time. But this is not true.
Without the sleep, the lock is only hold until the test finishes, which will be some milliseconds at best. If you run 5 tests in parallel, paratest needs to spawn one new process per test and spawning a process is expensive (depending on your system but probably longer than finishing the already running test).
So while your second test is still waiting for its process to spawn, the first test has already finished.

The sleep expands the timespan for a "conflicting" lock to those milliseconds + 1 second. And obviously, your system is able to spawn all other testprocesses within this timespan, resulting in one successful lock and 4 unsuccessful locks.

Relying on this neat timing of concurrency results in very unstable tests, so you shouldn't do that.

**Comment by mmamedov** [comment]
> it looks like you assume all tests start at exactly the same time. But this is not true.

@julianseeger Thanks, that's all I needed to know. It explains it.
Nevertheless, paratest helped me in successfully testing flock() with sleep(1). That 1 second sleep on lock, made all other parallel processes to fall into that 1 second where lock was in place. As expected function returned false for all those processes.

As you explained, since parallel tests do not start at the same time, without sleep() that microsecond of lock time is missed, and tests results were incorrect.

Thanks.

**Comment by julianseeger** [comment]
you're welcome ;)
