### ISSUE TITLE
Fatal error, when collecting coverage on PHP 5.6

### ISSUE THREAD

**Issue by aik099** [brianium/paratest#209]
When I run PHPUnit 5.4.2 on PHP 5.6 using Paratest I'm getting following errors:

```
PHP Catchable fatal error:  Argument 1 passed to ParaTest\Coverage\CoverageMerger::addCoverage() must be an instance of PHP_CodeCoverage, instance of SebastianBergmann\CodeCoverage\CodeCoverage given, called in /home/travis/build/qa-tools/qa-tools/vendor/brianium/paratest/src/ParaTest/Runners/PHPUnit/BaseRunner.php on line 212 and defined in /home/travis/build/qa-tools/qa-tools/vendor/brianium/paratest/src/ParaTest/Coverage/CoverageMerger.php on line 12
```

See https://travis-ci.org/qa-tools/qa-tools/jobs/135858201

This seems to be a recent issue, because last week that build passed.

**Comment by julianseeger** [comment]
Did you try 0.13.2 or dev-master?
https://github.com/brianium/paratest/pull/207 is addressing this problem but currently wip

**Comment by aik099** [comment]
> Did you try 0.13.2 or dev-master?

Nope. It's not that bad, because strangely test on all other PHP versions pass.

> #207 is addressing this problem but currently wip

I'll just wait for it to be finished then. Or maybe lock to a specific PHPCov version.

**Comment by michaelbutler** [comment]
Fixed in https://github.com/brianium/paratest/pull/208

**Comment by julianseeger** [comment]
At lest the `Or maybe lock to a specific PHPCov version.` is now done by paratest. For phpcc 4 support we have #211
