### ISSUE TITLE
How do I make sure I run two tests within the same thread?

### ISSUE THREAD

**Issue by rohan0793** [brianium/paratest#222]
So I working with testing my emails using mailtrap and I am running into a weird issue where I fetch the last email to check if the sent email was correct. But since the threads run different tests together, the emails get mixed up between tests. How to make sure that certain tests are run in a single thread whatsoever?

**Comment by gabrielpreston** [comment]
You'll want to refactor your logic to send emails to unique inboxes per test and then only check that specific inbox.

**Comment by rohan0793** [comment]
But I am on the free plan and I only have 1 inbox to my disposal. I guess I'll have to upgrade my plan.
