### ISSUE TITLE
Start testing this in PHP 7.2

### ISSUE THREAD

**Issue by TysonAndre** [brianium/paratest#239]
https://wiki.php.net/rfc/deprecations_php_7_2 mention `each()` will be deprecated in PHP 7.2, saw it used in src or test/

**Comment by julianseeger** [comment]
FTR:
Deprecated in 7.2 means we'll get warnings (or notices?) about December this Year (https://wiki.php.net/todo/php72).
The mentioned methods will be removed in 8.0 according to the rfc.

**Comment by Slamdunk** [comment]
Closed with https://github.com/brianium/paratest/pull/260
