### ISSUE TITLE
Composer Install Option for php 5.6 <= no longer available

### ISSUE THREAD

**Issue by Jonathonbyrd** [brianium/paratest#242]
Brief
--
I just noticed today a new error that's preventing my sauce tests from running. Here's the message:

>  Problem 1
>    - Installation request for brianium/paratest dev-master -> satisfiable by brianium/paratest[dev-master].
>    - brianium/paratest dev-master requires php >=7.0 -> your PHP version (5.6.24) does not satisfy that requirement.
>  Problem 2
>    - sauce/sausage 0.15.2 requires brianium/paratest >=0.6.1 -> satisfiable by brianium/paratest[dev-master].
>    - sauce/sausage 0.15.3 requires brianium/paratest >=0.6.1 -> satisfiable by brianium/paratest[dev-master].
>    - sauce/sausage 0.15.4 requires brianium/paratest >=0.6.1 -> satisfiable by brianium/paratest[dev-master].
>    - sauce/sausage 0.16.0 requires brianium/paratest >=0.6.1 -> satisfiable by brianium/paratest[dev-master].
>    - sauce/sausage 0.16.1 requires brianium/paratest >=0.12.1 -> satisfiable by brianium/paratest[dev-master].
>    - sauce/sausage 0.17.0 requires brianium/paratest >=0.12.1 -> satisfiable by brianium/paratest[dev-master].
>    - brianium/paratest dev-master requires php >=7.0 -> your PHP version (5.6.24) does not satisfy that requirement.
>    - Installation request for sauce/sausage >=0.15.2 -> satisfiable by sauce/sausage[0.15.2, 0.15.3, 0.15.4, 0.16.0, 0.16.1, 0.17.0].

Travis is running into this error when trying to install composer. Here's a screenshot:
![screenshot-130](https://user-images.githubusercontent.com/205828/27159305-c6203c28-5120-11e7-964e-9312c398ba86.png)

I have PHP 5.6.23 installed with this Travis run. I'm using the following installation command as suggested by the README.md file in this repo.
```
"require": {
    "brianium/paratest": "dev-master"
}
```

**Is there another composer option that I can use to install the PHP 5.6 version of paratest?**

**Comment by willemstuursma** [comment]
You should change this to:
```
"require-dev": {
    "brianium/paratest": "^0.15"
}
```
