### ISSUE TITLE
Start using php7 `declare(strict_types=1)` in this library?

### ISSUE THREAD

**Issue by TysonAndre** [brianium/paratest#252]
This helps catch errors earlier (e.g. passing an `int` to a function expecting a `string`)

**Comment by julianseeger** [comment]
Didn't use it before. Do you have to declare it in every file or just in the file that is the starting point?
It generally sounds good to me but I would expect a lot of pain. Even floats that are passed where ints are expected generate errors ^^ So the easyer order seems to add type annotations everywhere and enable strict typing when the first step is completed

**Comment by TysonAndre** [comment]
https://secure.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.strict

It has to be in every file.

- When a line in a file with `declare(strict_types=1)` **calls** a function from same/another file/ an internal function, strict type checks are made on the argument.
- When a function in a file with `declare(strict_types=1)` returns a value, strict type checks are made on the returned value.

**Comment by julianseeger** [comment]
I dug a little bit deeper into the discussion behind that rfc and imho it would be a good addition. While staying fully backwards compatible, it could catch some edge cases that may not have been tested but are in the code that is executed during tests (paratests tests). It then should be added to all classes starting with the TestCases and include type hints where known, making type annotations superfluous, shouldn't it?

**Comment by Slamdunk** [comment]
This can be automatically done by https://github.com/brianium/paratest/pull/256
