### ISSUE TITLE
The reported version in the console is wrong

### ISSUE THREAD

**Issue by Multiply** [brianium/paratest#257]
When installing version 1.0.0 it reports back as 0.14.0.

Maybe this shouldn't be hardcoded in a file, but merely be read from the composer.json file, or something similar?

`php vendor/bin/paratest --version`

**Comment by julianseeger** [comment]
*manually bumped to 1.0.1*

Have you ever done or seen it being automatically read / parsed from composer?
The composer.json wouldn't be sufficient. The composer.lock could do but I'm not sure if we know the exact location for sure...

**Comment by ktomk** [comment]
`installed.json` has version and reference of a package installed. Here is a command-line example for the "`phpunit/phpunit`" package:

~~~
$ grep '"name": "phpunit/phpunit"' -A6 vendor/composer/installed.json
        "name": "phpunit/phpunit",
        "version": "6.2.3",
        "version_normalized": "6.2.3.0",
        "source": {
            "type": "git",
            "url": "https://github.com/sebastianbergmann/phpunit.git",
            "reference": "fa5711d0559fc4b64deba0702be52d41434cbcb7"
~~~

You can always find this file in the vendor folder which is a known location when installed as a package.
