### ISSUE TITLE
Percentage going over 100.

### ISSUE THREAD

**Issue by gnutix** [brianium/paratest#58]
Small issue I've noticed in the output for paratests : the percentage is often over 100.
Exemple: 

```
$ $(pwd)/vendor/bin/paratest -c $(pwd)/app/phpunit.xml.dist $(pwd)/src/
Running phpunit in 5 processes with /home/travis/build/project/vendor/bin/phpunit
Configuration read from /home/travis/build/project/app/phpunit.xml.dist
...............................................................  63 / 159 ( 39%)
............................................................... 126 / 159 ( 79%)
............................................................... 189 / 159 (118%)
......................
Time: 53 seconds, Memory: 12.75Mb
OK (211 tests, 1091 assertions)
```

As you can see here, the percentage shown is 118%. Any idea how this can happen?
Could it be because of skipped / incomplete / @depend tests ?

**Comment by julianseeger** [comment]
I would like to propose a fix for this issue at https://github.com/brianium/paratest/tree/percentage-fix
With the fix, every ExecutableTest knows the expected count of testmethods to be contained in the result. If the real results contain more tests than expected, the total count of tests is increased accordingly.
The phenomenon you can observe is that the total test count increases while running the dataProviders with an increasing percentage that will never get above 100%.

With https://github.com/aik099/qa-tools that now contains a total of 671 tests, it looks like this:
**Paratest:**
```
Running phpunit in 10 processes with */vendor/bin/phpunit

Configuration read from */qa-tools/phpunit.xml.dist

...............................................................  63 / 510 ( 12%)
............................................................... 126 / 538 ( 23%)
............................................................... 189 / 556 ( 33%)
............................................................... 252 / 576 ( 43%)
............................................................... 315 / 587 ( 53%)
............................................................... 378 / 602 ( 62%)
............................................................... 441 / 617 ( 71%)
............................................................... 504 / 631 ( 79%)
............................................................... 567 / 644 ( 88%)
............................................................... 630 / 662 ( 95%)
.........................................

Time: 2.64 seconds, Memory: 11.50Mb

OK (671 tests, 5153 assertions)
```

**PHPUnit:**
```
PHPUnit 4.4.1 by Sebastian Bergmann.

Configuration read from */qa-tools/phpunit.xml.dist

...............................................................  63 / 671 (  9%)
............................................................... 126 / 671 ( 18%)
............................................................... 189 / 671 ( 28%)
............................................................... 252 / 671 ( 37%)
............................................................... 315 / 671 ( 46%)
............................................................... 378 / 671 ( 56%)
............................................................... 441 / 671 ( 65%)
............................................................... 504 / 671 ( 75%)
............................................................... 567 / 671 ( 84%)
............................................................... 630 / 671 ( 93%)
.........................................

Time: 3.8 seconds, Memory: 45.50Mb

OK (671 tests, 5153 assertions)
```

**Summary:**
Cons:
- still wrong total count (at least at the beginning)

Pros:
- total count as accurate as paratest knows at the given time
- total count always higher than passed test count
- percentage always <= 100% (and never decreasing)

**Why not execute dataProviders in advance?**
Executing the dataProviders from paratest provides a different environment than executing them from phpunit. So this might harm the stability and applicability of paratest only in favor of a "better" text output (bad trade in my opinion). Likewise, executing phpunit twice per testcase only to get the correct count up-front will harm the effectiveness of paratest because process spawning is expensive.... again in favor of a better text output.
I think this fix is a fair tradeoff between representative progress output and simplicity.

Sorry for the wall of text but I would really like to get feedback on this ;)

**Comment by aik099** [comment]
In any case having <100% is better (except for shop discount :smile: ) then we have currently.

**Comment by brianium** [comment]
This is definitely an improvement. I don't think I am a fan of the idea of executing dataProviders in advance, for pretty much the same reasons @julianseeger mentioned above.

I wonder if we need perfect parity with PHPUnit here on text output? It seems reasonable to not have a total count available for concurrent tests. Would the usefulness of ParaTest be hurt if we removed the right side of the counts and the percentage?

```
PHPUnit 4.4.1 by Sebastian Bergmann.

Configuration read from */qa-tools/phpunit.xml.dist

...............................................................  63
............................................................... 126
............................................................... 189
............................................................... 252
............................................................... 315
............................................................... 378
............................................................... 441
............................................................... 504
............................................................... 567
............................................................... 630
.........................................

Time: 2.64 seconds, Memory: 11.50Mb

OK (671 tests, 5153 assertions)
```

**Comment by julianseeger** [comment]
>I wonder if we need perfect parity with PHPUnit here on text output? It seems reasonable to not have a total count available for concurrent tests. Would the usefulness of ParaTest be hurt if we removed the right side of the counts and the percentage?

The total count probably doesn't matter but the percentage seems to be of interest as a measure of progress. In #129 , @grongor even mentioned that he would prefer his own fork (that counts all dataProvider executions of a testmethod as one single test) over the paratest origin. The result is exactly this: correct/usable percentage but completely incorrect total count.

So we could make a tradeoff:

```
...............................................................  63 ( 12%)
............................................................... 126 ( 23%)
............................................................... 189 ( 33%)
............................................................... 252 ( 43%)
............................................................... 315 ( 53%)
............................................................... 378 ( 62%)
............................................................... 441 ( 71%)
............................................................... 504 ( 79%)
............................................................... 567 ( 88%)
............................................................... 630 ( 95%)
.........................................
```

**Comment by brianium** [comment]
I think that is totally acceptable. I certainly don't want to step on any toes if the majority of people using this prefer the `0/0` format - even if the numbers are incorrect.
