### ISSUE TITLE
Not working locally

### ISSUE THREAD

**Issue by aik099** [brianium/paratest#71]
My test suite runs 48 seconds locally. When executed locally with paratest it takes it 49 seconds to complete. However when executed on Travis it's executed 8 seconds.

Is there a way to detect why it's not working locally?

Also I've tried to run paratest tests locally and they're hanging in the middle of the process.

**Comment by julianseeger** [comment]
I'm going to close this now because it has become old.
For future reference: there is a section in our readme for "optimizing speed": https://github.com/brianium/paratest#optimizing-speed
That should cover the most important things.
