### ISSUE TITLE
Native implementation?

### ISSUE THREAD

**Issue by brianium** [brianium/paratest#81]
ParaTest has definitely solved some issues for me - particularly in the functional testing realm, and I am glad to see it has done the same for a bunch of other people.

I think it is becoming too cumbersome to rely on PHPUnit as a hard dependency. The benefit of this approach is you can run existing PHPUnit suites concurrently, but PHPUnit can introduce a breaking change - and I don't think it is worth the investment to have ParaTest fully support all PHPUnit configuration options.

I have been drawing up some ideas for a new test framework that has concurrency baked in. 

Any thoughts on converting ParaTest to a [READONLY] and beginning work on a new framework altogether (particularly one that can take advantage of php 5.5 coroutines and generators?)

**Comment by julianseeger** [comment]
As peridot is growing and paratest can increase it's focus on phpunit, I think we can close this now.
